// mirko.rahn@itwm.fraunhofer.de

#ifndef _FHG_UTIL_CPP_HEADER_GEN
#define _FHG_UTIL_CPP_HEADER_GEN 1

#include <iostream>

namespace fhg
{
  namespace util
  {
    namespace cpp
    {
      template<typename Stream>
      Stream& do_not_edit (Stream& s)
      {
        return s << "// DO NOT EDIT THIS FILE!" << std::endl;
      }

      template<typename Stream>
      Stream& header_gen (Stream& s)
      {
        s << "// bugs or questions: sdpa-dev@itwm.fraunhofer.de" << std::endl;
        s                                                        << std::endl;

        return s;
      }

      template<typename Stream>
      Stream& header_gen_full (Stream& s)
      {
        do_not_edit (s);
        header_gen (s);

        return s;
      }
    }
  }
}

#endif
