#!/usr/bin/python2.4
# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import service
from google.protobuf import service_reflection
from google.protobuf import descriptor_pb2
_ERRORCODE = descriptor.EnumDescriptor(
  name='ErrorCode',
  full_name='sdpa.messages.ErrorCode',
  filename='ErrorCode',
  values=[
    descriptor.EnumValueDescriptor(
      name='OK', index=0, number=0,
      options=None,
      type=None),
  ],
  options=None,
)


_JOBSTATE = descriptor.EnumDescriptor(
  name='JobState',
  full_name='sdpa.messages.JobState',
  filename='JobState',
  values=[
    descriptor.EnumValueDescriptor(
      name='UNKNOWN', index=0, number=0,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='PENDING', index=1, number=1,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='RUNNING', index=2, number=2,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='FINISHED', index=3, number=3,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='FAILED', index=4, number=4,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='CANCELLED', index=5, number=5,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='CANCELLING', index=6, number=6,
      options=None,
      type=None),
  ],
  options=None,
)


OK = 0
UNKNOWN = 0
PENDING = 1
RUNNING = 2
FINISHED = 3
FAILED = 4
CANCELLED = 5
CANCELLING = 6



_SDPAMESSAGE = descriptor.Descriptor(
  name='SDPAMessage',
  full_name='sdpa.messages.SDPAMessage',
  filename='sdpa-msg.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='error', full_name='sdpa.messages.SDPAMessage.error', index=0,
      number=1, type=11, cpp_type=10, label=1,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='submit_job', full_name='sdpa.messages.SDPAMessage.submit_job', index=1,
      number=2, type=11, cpp_type=10, label=1,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='submit_job_ack', full_name='sdpa.messages.SDPAMessage.submit_job_ack', index=2,
      number=3, type=11, cpp_type=10, label=1,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='cancel_job', full_name='sdpa.messages.SDPAMessage.cancel_job', index=3,
      number=4, type=11, cpp_type=10, label=1,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='cancel_job_ack', full_name='sdpa.messages.SDPAMessage.cancel_job_ack', index=4,
      number=5, type=11, cpp_type=10, label=1,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='job_status_request', full_name='sdpa.messages.SDPAMessage.job_status_request', index=5,
      number=6, type=11, cpp_type=10, label=1,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='job_status', full_name='sdpa.messages.SDPAMessage.job_status', index=6,
      number=7, type=11, cpp_type=10, label=1,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='job_finished', full_name='sdpa.messages.SDPAMessage.job_finished', index=7,
      number=8, type=11, cpp_type=10, label=1,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='job_finished_ack', full_name='sdpa.messages.SDPAMessage.job_finished_ack', index=8,
      number=9, type=11, cpp_type=10, label=1,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='job_failed', full_name='sdpa.messages.SDPAMessage.job_failed', index=9,
      number=10, type=11, cpp_type=10, label=1,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='job_failed_ack', full_name='sdpa.messages.SDPAMessage.job_failed_ack', index=10,
      number=11, type=11, cpp_type=10, label=1,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='life_signal', full_name='sdpa.messages.SDPAMessage.life_signal', index=11,
      number=12, type=11, cpp_type=10, label=1,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='config_request', full_name='sdpa.messages.SDPAMessage.config_request', index=12,
      number=13, type=11, cpp_type=10, label=1,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='config_reply', full_name='sdpa.messages.SDPAMessage.config_reply', index=13,
      number=14, type=11, cpp_type=10, label=1,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_ERROR = descriptor.Descriptor(
  name='Error',
  full_name='sdpa.messages.Error',
  filename='sdpa-msg.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='error_code', full_name='sdpa.messages.Error.error_code', index=0,
      number=1, type=14, cpp_type=8, label=2,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='error_description', full_name='sdpa.messages.Error.error_description', index=1,
      number=2, type=9, cpp_type=9, label=2,
      default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_TOKEN = descriptor.Descriptor(
  name='Token',
  full_name='sdpa.messages.Token',
  filename='sdpa-msg.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='place', full_name='sdpa.messages.Token.place', index=0,
      number=1, type=12, cpp_type=9, label=2,
      default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='token', full_name='sdpa.messages.Token.token', index=1,
      number=2, type=12, cpp_type=9, label=2,
      default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_SUBMITJOB = descriptor.Descriptor(
  name='SubmitJob',
  full_name='sdpa.messages.SubmitJob',
  filename='sdpa-msg.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='workflow', full_name='sdpa.messages.SubmitJob.workflow', index=0,
      number=1, type=12, cpp_type=9, label=2,
      default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='input', full_name='sdpa.messages.SubmitJob.input', index=1,
      number=2, type=11, cpp_type=10, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_SUBMITJOBACK = descriptor.Descriptor(
  name='SubmitJobAck',
  full_name='sdpa.messages.SubmitJobAck',
  filename='sdpa-msg.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='job_id', full_name='sdpa.messages.SubmitJobAck.job_id', index=0,
      number=1, type=12, cpp_type=9, label=2,
      default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_CANCELJOB = descriptor.Descriptor(
  name='CancelJob',
  full_name='sdpa.messages.CancelJob',
  filename='sdpa-msg.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='job_id', full_name='sdpa.messages.CancelJob.job_id', index=0,
      number=1, type=12, cpp_type=9, label=2,
      default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='reason', full_name='sdpa.messages.CancelJob.reason', index=1,
      number=2, type=9, cpp_type=9, label=1,
      default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_CANCELJOBACK = descriptor.Descriptor(
  name='CancelJobAck',
  full_name='sdpa.messages.CancelJobAck',
  filename='sdpa-msg.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='job_id', full_name='sdpa.messages.CancelJobAck.job_id', index=0,
      number=1, type=12, cpp_type=9, label=2,
      default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_JOBSTATUSREQUEST = descriptor.Descriptor(
  name='JobStatusRequest',
  full_name='sdpa.messages.JobStatusRequest',
  filename='sdpa-msg.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='job_id', full_name='sdpa.messages.JobStatusRequest.job_id', index=0,
      number=1, type=12, cpp_type=9, label=2,
      default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_JOBSTATUSREPLY = descriptor.Descriptor(
  name='JobStatusReply',
  full_name='sdpa.messages.JobStatusReply',
  filename='sdpa-msg.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='job_id', full_name='sdpa.messages.JobStatusReply.job_id', index=0,
      number=1, type=12, cpp_type=9, label=2,
      default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='state', full_name='sdpa.messages.JobStatusReply.state', index=1,
      number=2, type=14, cpp_type=8, label=2,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_JOBFINISHED = descriptor.Descriptor(
  name='JobFinished',
  full_name='sdpa.messages.JobFinished',
  filename='sdpa-msg.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='job_id', full_name='sdpa.messages.JobFinished.job_id', index=0,
      number=1, type=12, cpp_type=9, label=2,
      default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_JOBFINISHEDACK = descriptor.Descriptor(
  name='JobFinishedAck',
  full_name='sdpa.messages.JobFinishedAck',
  filename='sdpa-msg.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='job_id', full_name='sdpa.messages.JobFinishedAck.job_id', index=0,
      number=1, type=12, cpp_type=9, label=2,
      default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_JOBFAILED = descriptor.Descriptor(
  name='JobFailed',
  full_name='sdpa.messages.JobFailed',
  filename='sdpa-msg.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='job_id', full_name='sdpa.messages.JobFailed.job_id', index=0,
      number=1, type=12, cpp_type=9, label=2,
      default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_JOBFAILEDACK = descriptor.Descriptor(
  name='JobFailedAck',
  full_name='sdpa.messages.JobFailedAck',
  filename='sdpa-msg.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='job_id', full_name='sdpa.messages.JobFailedAck.job_id', index=0,
      number=1, type=12, cpp_type=9, label=2,
      default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_LIFESIGNAL = descriptor.Descriptor(
  name='LifeSignal',
  full_name='sdpa.messages.LifeSignal',
  filename='sdpa-msg.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='timestamp', full_name='sdpa.messages.LifeSignal.timestamp', index=0,
      number=1, type=6, cpp_type=4, label=2,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='component_id', full_name='sdpa.messages.LifeSignal.component_id', index=1,
      number=2, type=12, cpp_type=9, label=2,
      default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_CONFIGREQUEST = descriptor.Descriptor(
  name='ConfigRequest',
  full_name='sdpa.messages.ConfigRequest',
  filename='sdpa-msg.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='component_id', full_name='sdpa.messages.ConfigRequest.component_id', index=0,
      number=1, type=12, cpp_type=9, label=2,
      default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_CONFIGREPLY = descriptor.Descriptor(
  name='ConfigReply',
  full_name='sdpa.messages.ConfigReply',
  filename='sdpa-msg.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='component_id', full_name='sdpa.messages.ConfigReply.component_id', index=0,
      number=1, type=12, cpp_type=9, label=2,
      default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_SDPAMESSAGE.fields_by_name['error'].message_type = _ERROR
_SDPAMESSAGE.fields_by_name['submit_job'].message_type = _SUBMITJOB
_SDPAMESSAGE.fields_by_name['submit_job_ack'].message_type = _SUBMITJOBACK
_SDPAMESSAGE.fields_by_name['cancel_job'].message_type = _CANCELJOB
_SDPAMESSAGE.fields_by_name['cancel_job_ack'].message_type = _CANCELJOBACK
_SDPAMESSAGE.fields_by_name['job_status_request'].message_type = _JOBSTATUSREQUEST
_SDPAMESSAGE.fields_by_name['job_status'].message_type = _JOBSTATUSREPLY
_SDPAMESSAGE.fields_by_name['job_finished'].message_type = _JOBFINISHED
_SDPAMESSAGE.fields_by_name['job_finished_ack'].message_type = _JOBFINISHEDACK
_SDPAMESSAGE.fields_by_name['job_failed'].message_type = _JOBFAILED
_SDPAMESSAGE.fields_by_name['job_failed_ack'].message_type = _JOBFAILEDACK
_SDPAMESSAGE.fields_by_name['life_signal'].message_type = _LIFESIGNAL
_SDPAMESSAGE.fields_by_name['config_request'].message_type = _CONFIGREQUEST
_SDPAMESSAGE.fields_by_name['config_reply'].message_type = _CONFIGREPLY
_ERROR.fields_by_name['error_code'].enum_type = _ERRORCODE
_SUBMITJOB.fields_by_name['input'].message_type = _TOKEN
_JOBSTATUSREPLY.fields_by_name['state'].enum_type = _JOBSTATE

class SDPAMessage(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _SDPAMESSAGE

class Error(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _ERROR

class Token(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _TOKEN

class SubmitJob(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _SUBMITJOB

class SubmitJobAck(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _SUBMITJOBACK

class CancelJob(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _CANCELJOB

class CancelJobAck(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _CANCELJOBACK

class JobStatusRequest(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _JOBSTATUSREQUEST

class JobStatusReply(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _JOBSTATUSREPLY

class JobFinished(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _JOBFINISHED

class JobFinishedAck(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _JOBFINISHEDACK

class JobFailed(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _JOBFAILED

class JobFailedAck(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _JOBFAILEDACK

class LifeSignal(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _LIFESIGNAL

class ConfigRequest(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _CONFIGREQUEST

class ConfigReply(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _CONFIGREPLY

