
DEP += sustack.xml
DEP += generate/package.xml
DEP += generate/slot.xml
DEP += print.hpp

###############################################################################

TRUNK = /amd/nfs/root/gpfs/u/r/rahn/SDPA/trunk

PNETC = $(TRUNK)/main/trunk/build45/xml/xml/parse/pnetc
WE_EXEC = $(TRUNK/main/trunk/build45/we/apps/we-exec
PNET2DOT = $(TRUNK)/main/trunk/build45/we/apps/pnet2dot

