// Copyright (C) 2026 Fraunhofer ITWM
// SPDX-License-Identifier: GPL-3.0-or-later

#include <boost/test/unit_test.hpp>

#include <gspc/drts/client.hpp>
#include <gspc/drts/drts.hpp>
#include <gspc/drts/scoped_rifd.hpp>

#include <gspc/testing/make.hpp>
#include <gspc/testing/parse_command_line.hpp>
#include <gspc/testing/scoped_nodefile_from_environment.hpp>
#include <gspc/testing/shared_directory.hpp>
#include <gspc/testing/source_directory.hpp>

#include <gspc/we/type/value.hpp>
#include <gspc/testing/printer/we/type/value.hpp>
#include <gspc/we/type/value/poke.hpp>

#include <gspc/util/temporary_path.hpp>
#include <gspc/testing/flatten_nested_exceptions.hpp>
#include <gspc/testing/printer/multimap.hpp>
#include <gspc/testing/random.hpp>
#include <gspc/testing/require_container_is_permutation.hpp>

#include <boost/multiprecision/cpp_int.hpp>
#include <boost/program_options.hpp>

#include <algorithm>
#include <filesystem>
#include <functional>
#include <map>
#include <random>
#include <string>

namespace
{
  // Generate a random bigint that may be outside the range of fixed-size
  // integral types. The value is generated by creating a random number of
  // random "limbs" (64-bit chunks) and combining them.
  gspc::pnet::type::value::bigint_type random_bigint()
  {
    auto& engine {gspc::testing::detail::GLOBAL_random_engine()};

    // Randomly decide if negative
    std::bernoulli_distribution is_negative (0.3);
    bool const negative {is_negative (engine)};

    // Random number of 64-bit limbs (1-4 gives us up to 256-bit numbers)
    std::uniform_int_distribution<int> num_limbs_dist (1, 4);
    int const num_limbs {num_limbs_dist (engine)};

    gspc::pnet::type::value::bigint_type result {0};
    std::uniform_int_distribution<std::uint64_t> limb_dist;

    for (int i {0}; i < num_limbs; ++i)
    {
      result <<= 64;
      result |= limb_dist (engine);
    }

    return negative ? -result : result;
  }

  std::string classify (gspc::pnet::type::value::bigint_type const& value)
  {
    if (value < 0)
    {
      return "negative";
    }
    if (value == 0)
    {
      return "zero";
    }
    if (value < 100)
    {
      return "small";
    }
    if (value < 1000)
    {
      return "medium";
    }
    return "large";
  }
}

BOOST_AUTO_TEST_CASE (share_example_bigint_condition)
{
  ::boost::program_options::options_description options_description;

  options_description.add (gspc::testing::options::shared_directory());
  options_description.add (gspc::testing::options::source_directory());
  options_description.add (gspc::options::installation());
  options_description.add (gspc::options::drts());
  options_description.add (gspc::options::scoped_rifd());

  ::boost::program_options::variables_map vm
    ( gspc::testing::parse_command_line
        ( ::boost::unit_test::framework::master_test_suite().argc
        , ::boost::unit_test::framework::master_test_suite().argv
        , options_description
        )
    );

  gspc::util::temporary_path const shared_directory
    (gspc::testing::shared_directory (vm) / "share_example_bigint_condition");

  gspc::testing::scoped_nodefile_from_environment const nodefile_from_environment
    (shared_directory, vm);

  vm.notify();

  gspc::installation const installation (vm);

  gspc::testing::make_net const make
    ( installation
    , "bigint_condition"
    , gspc::testing::source_directory (vm)
    );

  gspc::scoped_rifds const rifds ( gspc::rifd::strategy {vm}
                                 , gspc::rifd::hostnames {vm}
                                 , gspc::rifd::port {vm}
                                 , installation
                                 );

  gspc::scoped_runtime_system const drts
    (vm, installation, "worker:1", rifds.entry_points());

  auto const values
    { std::invoke
      ( [&]
        {
          auto _values {std::vector<gspc::pnet::type::value::bigint_type>{}};

          std::generate_n
            ( std::back_inserter (_values)
            , std::invoke (gspc::testing::random<std::size_t>{}, 1000, 0)
            , random_bigint
            );

          return _values;
        }
      )
    };

  auto const inputs
    { std::invoke
      ( [&]
        {
          auto _inputs
            { std::multimap<std::string, gspc::pnet::type::value::value_type>{}
            };

          std::transform
            ( std::begin (values), std::end (values)
            , std::inserter (_inputs, std::end (_inputs))
            , [] (auto const& value)
              {
                return std::make_pair (std::string {"value"}, value);
              }
            );

          return _inputs;
        }
      )
    };

  auto const result
    {gspc::client (drts).put_and_run (gspc::workflow (make.pnet()), inputs)};

  auto const make_classified
    { [] (gspc::pnet::type::value::bigint_type const& value, std::string const& classification)
      {
        gspc::pnet::type::value::value_type v;
        gspc::pnet::type::value::poke ("value", v, value);
        gspc::pnet::type::value::poke ("classification", v, classification);
        return v;
      }
    };

  auto const expected
    { std::invoke
      ( [&]
        {
          auto _expected
            { std::multimap<std::string, gspc::pnet::type::value::value_type>{}
            };

          std::transform
            ( std::begin (values), std::end (values)
            , std::inserter (_expected, std::end (_expected))
            , [&] (auto const& value)
              {
                return std::make_pair
                  ( std::string {"result"}
                  , make_classified (value, classify (value))
                  );
              }
            );

          return _expected;
        }
      )
    };

  GSPC_TESTING_REQUIRE_CONTAINER_IS_PERMUTATION (result, expected);
}
