MAIN = stresstest

###############################################################################

NOT_STARTS_WITH += generate
NOT_STARTS_WITH += dup

###############################################################################

ifndef SDPA_HOME
 $(error variable SDPA_HOME not set)
endif

include $(SDPA_HOME)/share/sdpa/make/common.mk
