#!/bin/sh

# get the list of nodes
nodes=
switch_to_master=0
rename_master=0
on_master=0
master=
node_name=`hostname`
start_fhglog=0
start_fvm=0

if [ -r "$PBS_NODEFILE" ]; then
	echo "Running on the initial master node..."
	on_master=1
	master="$node_name"
else
	echo "Running on slave $node_name..."
fi

if [ $on_master -eq 1 ]; then
	env_file="$HOME/.init-screen.env"

	echo "clearing .screen.env..."
	rm -f "$env_file"
	echo "writing environment info to $env_file..."
	echo export PBS_O_HOST="$PBS_O_HOST" >> "$env_file"
	echo export SDPA_MASTER="$node_name" >> "$env_file"
	echo export FHGLOG_to_server="$node_name" >> "$env_file"
	echo export FHGLOG_to_console="true" >> "$env_file"
	echo export DISPLAY="$DISPLAY" >> "$env_file"
fi

if [ $# -gt 0 ]; then
	nodes=$@
else
	if [ -r "$PBS_NODEFILE" ]; then
		echo "using nodes from $PBS_NODEFILE"
		nodes=`cat $PBS_NODEFILE | sort -u | grep -v "$master" | sort -n`
		nodes=`echo $master $nodes`
		rename_master=1
		switch_to_master=1
		start_fhglog=1
		start_fvm=1
	fi
fi

if [ -z "$nodes" ]; then
	echo "Nothing to do"
	exit 0
fi

headnode="$PBS_O_HOST"

if [ $start_fhglog -eq 1 ]; then
	killall fhglog-server
	echo "starting log-server on master node"
	ssh -t "$headnode" screen -D -RR -X "screen -t log ssh $master" # fhglog-server short"
fi

if [ $start_fvm -eq 1 ]; then
	echo "starting fvm-server on master node"
	ssh -t "$headnode" screen -D -RR -X "screen -t fvm ssh $master" # /opt/cluster/PV-4D.pspro/bin/petry/fvm_sdpa_standalone"
	ssh -t "$headnode" screen -D -RR -X "screen -t orch ssh $master"
	ssh -t "$headnode" screen -D -RR -X "screen -t agg ssh $master"
fi


if [ -z "$headnode" ]; then
	echo "I don't know what my headnode is"
	exit 1
fi

numnodes=`echo $nodes | wc -w`
maxnodes=10

if [ $numnodes -gt $maxnodes ]; then
	echo -n "do you really want to start screen sessions on $numnodes nodes (configured maximum=$maxnodes)? [y/N]: "
	read answer
	case "$answer" in
		y|Y|yes|Yes)
			echo "ok, I'll do as you whish"
			;;
		*)
			echo "Puh."
			exit 0
			;;
	esac
fi
echo "going to start screen session on nodes:" $nodes

echo -n 'starting sessions...'
for n in $nodes; do
	title="$n"

	if [ $rename_master -eq 1 -a x"$n" == x"$master" ]; then
		title="master:$n"
	fi
	echo -n " $n"
	if [ x"$n" == x"$master" ]; then
		ssh -t "$headnode" screen -D -RR -X "screen -t $title ssh $n"
		ssh -t "$headnode" screen -D -RR -X "screen -t $n ssh $n" &
	else
		ssh -t "$headnode" screen -D -RR -X "screen -t $title ssh $n" &
	fi
done
wait
echo

if [ $switch_to_master -eq 1 ]; then
	echo "switching to master-node screen"
	ssh "$headnode" screen -X select master
fi
