include(cmake_parse_arguments)
include(car_cdr_macros)

macro (FHG_ADD_RUNTIME_EXECUTABLE)
  PARSE_ARGUMENTS(EXECUTABLE "LINK_LIBRARIES;NAME" "" ${ARGN})
  CAR (EXECUTABLE_SOURCE ${EXECUTABLE_DEFAULT_ARGS})
  CDR (EXECUTABLE_ADDITIONAL_SOURCES ${EXECUTABLE_DEFAULT_ARGS})

  if (EXECUTABLE_NAME)
    set (exe_name ${EXECUTABLE_NAME})
  else()
    string (REGEX REPLACE "(.*)\\.c.*" "\\1" exe_name ${EXECUTABLE_SOURCE})
  endif()

  extended_add_executable (NAME "${exe_name}"
    SOURCES ${EXECUTABLE_SOURCE} ${EXECUTABLE_ADDITIONAL_SOURCES}
    LIBRARIES ${EXECUTABLE_LINK_LIBRARIES}
    DONT_APPEND_EXE_SUFFIX
    INSTALL
  )
endmacro()
