set(Boost_FIND_QUIETLY NO)
set(Boost_USE_STATIC_LIBS ON)
#set(Boost_USE_STATIC_LIBS OFF)

set (REQUIRED_COMPONENTS
  THREAD
  SYSTEM
  FILESYSTEM
  SERIALIZATION
  PROGRAM_OPTIONS
  IOSTREAMS
  DATE_TIME
)
set (REQUIRED_UNITTEST_COMPONENTS
  TEST_EXEC_MONITOR
  UNIT_TEST_FRAMEWORK
)

find_package (Boost 1.45 REQUIRED
  COMPONENTS ${REQUIRED_COMPONENTS} ${REQUIRED_UNITTEST_COMPONENTS}
)

# Boost_LIBRARIES is already set,
# but we split them for being able to link to unit tests only.
set (Boost_LIBRARIES "")
foreach (REQUIRED_COMPONENT ${REQUIRED_COMPONENTS})
  set (Boost_LIBRARIES
    ${Boost_LIBRARIES} ${Boost_${REQUIRED_COMPONENT}_LIBRARY}
  )
endforeach (REQUIRED_COMPONENT ${Boost_REQUIRED_COMPONENTS})

set (Boost_UNIT_TEST_LIBRARIES "")
foreach (REQUIRED_COMPONENT ${REQUIRED_UNITTEST_COMPONENTS})
  set (Boost_UNIT_TEST_LIBRARIES
    ${Boost_UNIT_TEST_LIBRARIES} ${Boost_${REQUIRED_COMPONENT}_LIBRARY}
  )
endforeach (REQUIRED_COMPONENT ${Boost_REQUIRED_COMPONENTS})
