before_script:
  - set -euo pipefail
  - ci_scripts_dir="${PWD}/.ci"
  - source "${ci_scripts_dir}/env/${HOSTNAME}"

  - git submodule update --init --recursive

  - source "${ci_scripts_dir}/jobs/before"

build (centos 5.7):
  stage: build
  extends:
    - .legacy_before_script
  script:
    - source "${ci_scripts_dir}/jobs/build"
  tags:
    - centos-5.7

build (centos 6.5):
  stage: build
  script:
    - source "${ci_scripts_dir}/jobs/build"
  tags:
    - centos-6.5

tests (centos 5.7):
  stage: test
  extends:
    - .legacy_before_script
  script:
    - source "${ci_scripts_dir}/jobs/test.common"
    - source "${ci_scripts_dir}/jobs/test"
  tags:
    - centos-5.7

tests (centos 6.5):
  stage: test
  script:
    - source "${ci_scripts_dir}/jobs/test.common"
    - source "${ci_scripts_dir}/jobs/test"
  tags:
    - centos-6.5

#! \todo add virtual memory tests on centos 5.7: needs infiniband or
#        gpi2+eth (requires higher kernel version)

virtual memory tests (centos 6.5):
  stage: test
  script:
    - source "${ci_scripts_dir}/jobs/test.common"
    - source "${ci_scripts_dir}/jobs/virtual_memory_test"
  tags:
    - centos-6.5

performance tests (centos 5.7):
  stage: test
  extends:
    - .legacy_before_script
  script:
    - source "${ci_scripts_dir}/jobs/test.common"
    - source "${ci_scripts_dir}/jobs/performance_test"
  allow_failure: true
  tags:
    - centos-5.7

performance tests (centos 6.5):
  stage: test
  script:
    - source "${ci_scripts_dir}/jobs/test.common"
    - source "${ci_scripts_dir}/jobs/performance_test"
  allow_failure: true
  tags:
    - centos-6.5

.legacy_before_script:
  variables:
    GIT_SUBMODULE_STRATEGY: none
  before_script:
    - set -euo pipefail
    - ci_scripts_dir="${PWD}/.ci"
    - source "${ci_scripts_dir}/env/${HOSTNAME}"
    # curl is too old, so cloning fails via http, so enforce ssh
    - sed -i'' -e 's,url = ../../,url = git@gitlab.hpc.devnet.itwm.fhg.de:,'
           .gitmodules
    - git submodule update --init --recursive
    - source "${ci_scripts_dir}/jobs/before"
