before_script:
  - set -euo pipefail
  - ci_scripts_dir="${PWD}/.ci"
  - source "${ci_scripts_dir}/env/${HOSTNAME}"

  - git submodule update --init --recursive

  - source "${ci_scripts_dir}/jobs/before"

build (centos 5.7):
  stage: build
  script:
    - source "${ci_scripts_dir}/jobs/build"
  tags:
    - centos-5.7

build (centos 6.5):
  stage: build
  script:
    - source "${ci_scripts_dir}/jobs/build"
  tags:
    - centos-6.5

build (sles 12sp4):
  stage: build
  before_script:
    - zypper in git-core
  script:
    - source "${ci_scripts_dir}/jobs/build"
  tags:
    - sles12sp4

tests (centos 5.7):
  stage: test
  script:
    - source "${ci_scripts_dir}/jobs/test.common"
    - source "${ci_scripts_dir}/jobs/test"
  tags:
    - centos-5.7

tests (centos 6.5):
  stage: test
  script:
    - source "${ci_scripts_dir}/jobs/test.common"
    - source "${ci_scripts_dir}/jobs/test"
  tags:
    - centos-6.5

tests (sles 12sp4):
  stage: test
  script:
    - source "${ci_scripts_dir}/jobs/test.common"
    - source "${ci_scripts_dir}/jobs/test"
  tags:
    - sles12sp4

#! \todo add virtual memory tests on centos 5.7: needs infiniband or
#        gpi2+eth (requires higher kernel version)

virtual memory tests (centos 6.5):
  stage: test
  script:
    - source "${ci_scripts_dir}/jobs/test.common"
    - source "${ci_scripts_dir}/jobs/virtual_memory_test"
  tags:
    - centos-6.5

virtual memory tests (sles 12sp4):
  stage: test
  script:
    - source "${ci_scripts_dir}/jobs/test.common"
    - source "${ci_scripts_dir}/jobs/virtual_memory_test"
  tags:
    - sles12sp4

performance tests (centos 5.7):
  stage: test
  script:
    - source "${ci_scripts_dir}/jobs/test.common"
    - source "${ci_scripts_dir}/jobs/performance_test"
  allow_failure: true
  tags:
    - centos-5.7

performance tests (centos 6.5):
  stage: test
  script:
    - source "${ci_scripts_dir}/jobs/test.common"
    - source "${ci_scripts_dir}/jobs/performance_test"
  allow_failure: true
  tags:
    - centos-6.5

performance tests (sles 12sp4):
  stage: test
  script:
    - source "${ci_scripts_dir}/jobs/test.common"
    - source "${ci_scripts_dir}/jobs/performance_test"
  allow_failure: true
  tags:
    - sles12sp4
