theme: minima

title: GPI-Space
description: Memory Driven Computing
logo: /assets/img/logo/250x78-gpi-space.jpg
company_logo: /assets/img/logo/itwm.svg
default_avatar: /assets/img/avatar/230x230-default.svg

editors:
  - Max Zeyen

releases:
  - v22.12
  - v22.09
  - v22.06
  - v22.06
  - v22.03
  - v21.12.1
  - v21.12
  - v21.09
  - v21.06

show_downloads: true

show_excerpts: false

minima:
  date_format: "%b %-d, %Y"

baseurl: /

plugins:
  - jekyll-feed
  - jekyll-seo-tag
