theme: minima

title: GPI-Space
description: Memory Driven Computing
logo: /assets/img/logo/250x78-gpi-space.jpg
company_logo: /assets/img/logo/itwm.svg

editors:
  - Max Zeyen

show_downloads: true
download_branch: v21.03

show_excerpts: false

minima:
  date_format: "%b %-d, %Y"

baseurl: /

plugins:
  - jekyll-feed
  - jekyll-seo-tag

# urls entry:
#   required:
#     text
#     url
urls:
  - text: Home
    url: /
  - text: Features
    url: /features
  - text: Applications
    url: /applications
  - text: Installation
    url: /installation
  - text: How to Use
    url: /how-to-use
  - text: Contact
    url: /contact

# contacts entry:
#   required:
#     name
#     email
#   optional:
#     title
#     avatar
#     phone
#     address
#
# address entry:
#   required:
#     street
#     zipcode
#     city
#   optional:
#     company
#     state
#     country
default_avatar: /assets/img/avatar/230x230-default.svg
contacts:
  - title: Dr.
    name: Rui Màrio Silva Machado
    avatar: /assets/img/avatar/230X230-itwm-hpc-da-silva-machado-rui-mario-.jpg
    email: rui.machado
    phone: +49 631 31600-4392
    address:
      company: Fraunhofer-Institut für Techno- und Wirtschaftsmathematik ITWM
      street: Fraunhofer-Platz 1
      zipcode: 67663
      city: Kaiserslautern
      country: Germany
  - title: Dr.
    name: Mirko Rahn
    avatar: /assets/img/avatar/230X230-itwm-hpc-rahn-mirko.jpg
    email: mirko.rahn
    address:
      company: Fraunhofer-Institut für Techno- und Wirtschaftsmathematik ITWM
      street: Fraunhofer-Platz 1
      zipcode: 67663
      city: Kaiserslautern
      country: Germany
  - title: Dr.
    name: Franz-Josef Pfreundt
    avatar: /assets/img/avatar/230X230-itwm-hpc-pfreundt-franz-josef.jpg
    email: franz-josef.pfreundt
    phone: +49 631 31600-4459
    address:
      company: Fraunhofer-Institut für Techno- und Wirtschaftsmathematik ITWM
      street: Fraunhofer-Platz 1
      zipcode: 67663
      city: Kaiserslautern
      country: Germany
