#!/bin/bash
num_pcd=1
if [ $# -gt 0 ]
then
   num_pcd=$1
   shift
fi

killall nre-pcd
sleep 1
for i in $(seq 0 $( expr $num_pcd - 1 ) )
do
	:> pc.$i.txt
#	FHGLOG_level=MIN FHGLOG_to_file=pc.$i.txt run-pcd.fake -l 127.0.0.1:800$i /p/hpc/sdpa/fvm-pc/libexec/remig/*.so &
	FHGLOG_level=MIN run-pcd.fake -l 127.0.0.1:800$i /p/hpc/sdpa/fvm-pc/libexec/remig/*.so > pc.$i.txt 2>&1 &
done
