#!/bin/bash
#
# wrapper around a compiler similar to icecream
#
#
# 1. prepare job description
#
#      take prepared pnet (or compile if not present)
#
# 2. place tokens
#      working directory
#      parameters
#      compiler to use (name)
#      build-environment + md5sum
#
# 3. submit
#
#      wait until finished
#      check exit code token
#      print stdout
#      print stderr

prog_name=$(basename $0)
compiler="$prog_name"
c_compiler="gcc"
cxx_compiler="g++"

if [ -z "$SDPACFLAGS" ] ; then
   SDPACFLAGS="--network.timeout=10000 -t 25"
fi

if [ -n "$SDPACC_CC" ] ; then
    c_compiler="$SDPACC_CC"
fi
if [ -n "$SDPACC_CXX" ] ; then
    cxx_compiler="$SDPACC_CXX"
fi
if [ -z "$SDPA_HOME" ] ; then
    echo "SDPA must be be loaded and started! (SDPA_HOME is empty)" >&2
    exit 1
fi

# try to avoid cyclic execution of $self
mydir=$(readlink -f $(cd $(dirname $(which $0)) && pwd))
self="$mydir/$(basename $0)"

c_compiler=$(which -a "$c_compiler" | grep -v $mydir | head -n 1)
cxx_compiler=$(which -a "$cxx_compiler" | grep -v $mydir | head -n 1)

if [ -z "$c_compiler" ] ; then
    echo "sdpacc: could not locate real c compiler" >&2
    exit 2
fi

if [ -z "$cxx_compiler" ] ; then
    echo "sdpacc: could not locate real cxx compiler" >&2
    exit 2
fi

args="$@"
pnet="$SDPA_HOME/libexec/apps/sdpacc/compile.pnet"

pnet_tmp=$(mktemp)
result=
jobid=

trap 'cancel' EXIT

function isatty()
{
    local f="$1" ; shift
    f=$(readlink -f "$f")
    if [ -e "$f" ] ; then
	tty -s < "$f" >/dev/null 2>&1
	return $?
    else
	return 1
    fi
}

function cancel()
{
    if [ -z "$jobid" ] ; then
	return 0
    fi
    sdpac $SDPACFLAGS cancel "$jobid" &>/dev/null
    sdpac $SDPACFLAGS wait "$jobid" &>/dev/null
    ec=$?
    sdpac $SDPACFLAGS delete "$jobid" &>/dev/null
    if [ -n "$result" ] ; then
	test -e "$result" && rm -f "$result"
    fi
    return $ec
}

function compile ()
{
    prepare
    execute
}

function prepare ()
{
    pnetput --if "${pnet}" --of "${pnet_tmp}" \
              -p compiler=\""$compiler"\" \
              -p params=\""$args"\" \
              -p working_directory=\""$PWD"\" \
              -p build_environment=\"\"
}

function execute ()
{
    err=$(sdpac $SDPACFLAGS submit ${pnet_tmp} 2>&1)
    ec=$?
    test -e "${pnet_tmp}" && rm -f "${pnet_tmp}"
    if [ $ec -ne 0 ] ; then
	echo "submission failed: $ec: $err" >&2
	return $ec
    fi
    jobid="$err"
    err=$(sdpac $SDPACFLAGS wait "$jobid" 2>&1)
    ec=$?
    if [ $ec -ne 0 ] ; then
	echo "job failed: $ec: $err" >&2
	return $ec
    fi
    result=$(mktemp)
    err=$(sdpac $SDPACFLAGS -f -o "$result" results "${jobid}" 2>&1)
    ec=$?
    if [ $ec -ne 0 ] ; then
	echo "could not get results: $ec: $err" >&2
	return $ec
    fi

    to_be_deleted="${jobid}"
    jobid=
    err=$(sdpac $SDPACFLAGS delete "${to_be_deleted}" 2>&1)
    ec=$?
    if [ $ec -ne 0 ] ; then
	echo "could not delete job: $ec: $err" >&2
    fi

    std_out=$(pnetget < "$result" --type=output std_out | sed -e 's/^"//g' -e 's/"$//g')
    std_err=$(pnetget < "$result" --type=output std_err | sed -e 's/^"//g' -e 's/"$//g')
    ec=$(pnetget < "$result" --type=output exit_code | tr -d L)
    test -e "$result" && rm -f "$result"

    if [ -n "$std_out" ] ; then
	echo -e "$std_out"
    fi
    if [ -n "$std_err" ] ; then
        co=
        nc=
        if isatty /dev/stderr ; then
	    co='\033[0;35m'
            nc="\033[0m"
        fi
	echo -e "${co}$std_err${nc}" >&2
    fi

    unset jobid
    unset result
    return $ec
}

case "$prog_name" in
    *cc)
	compiler="$c_compiler"
	;;
    *++)
	compiler="$cxx_compiler"
	;;
    *)
	echo "E: dunno how to behave as $prog_name" >&2
	exit 1
	;;
esac

compile $@
