
MAIN = map

###############################################################################

CXXINCLUDEPATHS += $(CURDIR)

###############################################################################

include $(MAKEFILE_PUT)

DEP += Makefile $(MAKEFILE_PUT)

###############################################################################

ifndef SDPA_HOME
 $(error variable SDPA_HOME not set)
endif

include $(SDPA_HOME)/share/sdpa/make/common.mk
