#ifndef UNIVERSALQT
#define UNIVERSALQT

#include <QApplication>
#include <QCheckBox>
#include <QColorDialog>
#include <QComboBox>
#include <QCursor>
#include <QCustomEvent>
#include <QDesktopWidget>
#include <QDialog>
#include <QDir>
#include <QEvent>
#include <QFile>
#include <QFlags>
#include <QFont>
#include <QFontDatabase>
#include <QFontDialog>
#include <QGridLayout>
#include <QGroupBox>
#include <QImage>
#include <QLabel>
#include <QLayout>
#include <QLineEdit>
#include <QMainWindow>
#include <QMenuBar>
#include <QMessageBox>
#include <QMdiSubWindow>
#include <QMouseEvent>
#include <QObject>
#include <QPainter>
#include <QPalette>
#include <QPicture>
#include <QPixmap>
#include <QWhatsThis>
#include <QPushButton>
#include <QRadioButton>
#include <QSignalMapper>
#include <QSlider>
#include <QSpinBox>
#include <QString>
#include <QStyle>
#include <QStyleFactory>
#include <QTabWidget>
#include <QTextEdit>
#include <QtGui>
#include <QTimer>
#include <QToolTip>
#include <QToolBox>


#include <QValidator>
#include <QWidget>
#include <QWindowsStyle>
#include <QWorkspace>
#endif