
MAIN = put_get

###############################################################################

ifndef SDPA_HOME
 $(error variable SDPA_HOME not set)
endif

include $(SDPA_HOME)/share/sdpa/make/common.mk

WE_EXEC_LIBPATHS = $(SDPA_HOME)/libexec/sdpa
