
MAIN = expr_eliminate_bug

###############################################################################

PNETC_OPTS += --Omerge-expressions false

###############################################################################

ifndef SDPA_HOME
 $(error variable SDPA_HOME not set)
endif

include $(SDPA_HOME)/share/sdpa/make/common.mk
