
MAIN = inner_template_specialization

###############################################################################

PUT_PORT += x=10

###############################################################################


ifndef SDPA_HOME
 $(error variable SDPA_HOME not set)
endif

include $(SDPA_HOME)/share/sdpa/make/common.mk
