all:
	$(MAKE) -C datastructures
	$(MAKE) -C fvm
	$(MAKE) -C modules
	$(MAKE) -C pc

clean:
	rm -rf objs/*.o
	$(MAKE) -C datastructures clean
	$(MAKE) -C fvm clean
	$(MAKE) -C modules clean
	$(MAKE) -C pc clean

