#!/bin/sh

# get the list of nodes
nodes=
switch_to_master=0
rename_master=0
on_master=0
master=
node_name=`hostname`

if [ -r "$PBS_NODEFILE" ]; then
	echo "Running on the master node..."
	on_master=1
	master="$node_name"
else
	echo "Running on slave $node_name..."
fi

if [ $on_master -eq 1 ]; then
	env_file="$HOME/.init-screen.env"

	echo "clearing .screen.env..."
	rm -f "$env_file"
	echo "writing environment info to $env_file..."
	echo export PBS_SERVER="$PBS_SERVER" >> "$env_file"
	echo export FHGLOG_to_server="$node_name" >> "$env_file"
fi

if [ $# -gt 0 ]; then
	nodes=$@
else
	if [ -r "$PBS_NODEFILE" ]; then
		echo "using nodes from $PBS_NODEFILE"
		nodes=`cat $PBS_NODEFILE | grep -v "$master" | sort -n | uniq`
		nodes=`echo $master $nodes`
		rename_master=1
		switch_to_master=1
	fi
fi
if [ -z "$nodes" ]; then
	echo "Nothing to do"
	exit 0
fi

headnode="$PBS_SERVER"

if [ -z "$headnode" ]; then
	echo "I don't know what my headnode is"
	exit 1
fi

numnodes=`echo $nodes | wc -w`
maxnodes=10

if [ $numnodes -gt $maxnodes ]; then
	echo -n "do you really want to start screen sessions on $numnodes nodes (configured maximum=$maxnodes)? [y/N]: "
	read answer
	case "$answer" in
		y|Y|yes|Yes)
			echo "ok, I'll do as you whish"
			;;
		*)
			echo "Puh."
			exit 0
			;;
	esac
fi
echo "going to start screen session on nodes:" $nodes

echo -n 'starting sessions...'
for n in $nodes; do
	title="$n"

	if [ $rename_master -eq 1 -a x"$n" == x"$master" ]; then
		title="master:$n"
	fi
	echo -n " $n"
	if [ x"$n" == x"$master" ]; then
		ssh "$headnode" screen -X "screen -t "$title" ssh $n"
	else
		ssh "$headnode" screen -X "screen -t "$title" ssh $n" &
	fi
done
wait
echo

if [ $switch_to_master -eq 1 ]; then
	echo "switching to master-node screen"
	ssh "$headnode" screen -X select "master"
fi
