
MAIN = modulecall_with_multiple_occurences

###############################################################################

PNETC_OPTS += --Windependent-transition 0

ifndef SDPA_HOME
 $(error variable SDPA_HOME not set)
endif

include $(SDPA_HOME)/share/sdpa/make/common.mk
