// mirko.rahn@itwm.fraunhofer.de

#ifndef _FHG_UTIL_CPP_HEADER_GEN
#define _FHG_UTIL_CPP_HEADER_GEN 1

#include <iostream>

namespace fhg
{
  namespace util
  {
    namespace cpp
    {
      inline std::ostream & do_not_edit (std::ostream & os)
      {
        os << "// DO NOT EDIT THIS FILE!" << std::endl;

        return os;
      }

      inline std::ostream & header_gen (std::ostream & os)
      {
        os << "// bugs or questions: sdpa-dev@itwm.fraunhofer.de" << std::endl;
        os                                                        << std::endl;

        return os;
      }

      inline std::ostream & header_gen_full (std::ostream & os)
      {
        do_not_edit (os);
        header_gen (os);

        return os;
      }
    }
  }
}

#endif
