#!/bin/sh

# This script is used on dell02.hpc.devnet for running the Nightly build of PreStackPro.
# It is executed via cron as user pspro (see crontab -e).
#
# It sets up some required environment variables, starts Xvnc so an X is available for the tests,
# then runs ctest which does the actual building and testing and kills Xvnc again afterwards.


# only do something on dell02 (and not on dell01, 03 and 04)
host=`hostname`
if [ "$host" != "build_suse11" ]; then
  exit
fi

export CTEST=/usr/bin/ctest

unset http_proxy

echo "Running ctest"

$CTEST -S /home/projects/sdpa/Dashboards/SDPANightly.cmake -V -VV

