#!/bin/sh

# This script is used on dell02.hpc.devnet to run the Continuous build of PreStackPro.
# It is started via cron as user pspro (see crontab -e).
# It sets up some required environment variables, sets up the Intel compiler, and then runs ctest.

have_intel=no
host=`hostname | sed -e 's%build_.*%build%' -e 's%build-.*%build%'`

check_host() {
  which rpm > /dev/null 2>&1
  rc=$?
  if [ "$rc" !=  "0" ]; then
    echo "Not an rpm based system."
  else
    dummy=`rpm -qf /etc/issue`
    case "$dummy" in
      sles-release*)
        #export QTDIR=/opt/qt/4.4.3
        export QTDIR=/home/projects/sdpa/external_software/qt/4.7.1/
	export PATH=${QTDIR}/bin:$PATH
        export PKG_CONFIG_PATH=${QTDIR}/lib/pkgconfig:$PKG_CONFIG_PATH
        echo "Is SLES"
        ;;
      openSUSE-release*)
	export QTDIR=/home/projects/sdpa/external_software/qt/4.7.1/
        export PATH=${QTDIR}/bin:$PATH
        export PKG_CONFIG_PATH=${QTDIR}/lib/pkgconfig:$PKG_CONFIG_PATH
        echo "Is SUSE"
      ;;
      centos-release-5*)
        export QTDIR=/home/projects/sdpa/external_software/qt/4.7.1/
	export PATH=${QTDIR}/bin:$PATH
        export PKG_CONFIG_PATH=${QTDIR}/lib/pkgconfig:$PKG_CONFIG_PATH
        echo "Is CentOS"
      ;;
      centos-release-6*)
        export QTDIR=/home/projects/sdpa/external_software/qt/4.7.1/
	export PATH=${QTDIR}/bin:$PATH
        export PKG_CONFIG_PATH=${QTDIR}/lib/pkgconfig:$PKG_CONFIG_PATH
        echo "Is CentOS"
      ;;
    esac
  fi

}


if [ "$host" != "build" ]; then
  exit
fi

check_host

#export PATH=/home/pspro/inst/bin:/usr/local/bin:/usr/bin:/usr/X11R6/bin:/bin:/opt/kde3/bin:/usr/lib/jvm/jre/bin:/usr/lib/mit/bin

export LANG=en_US.UTF-8
export CTEST=//usr/bin/ctest

unset http_proxy

echo "Running ctest"

# set additional directory where cmake will search for stuff:
#export CMAKE_PREFIX_PATH=/p/hpc/psp/vr3-nightly-test-support

$CTEST -V -S ${HOME}/Dashboards/SDPAContinuous.cmake
