#!/bin/sh

# This script is used on dell02.hpc.devnet for running the Nightly build of PreStackPro.
# It is executed via cron as user pspro (see crontab -e).
#
# It sets up some required environment variables, starts Xvnc so an X is available for the tests,
# then runs ctest which does the actual building and testing and kills Xvnc again afterwards.


# only do something on dell02 (and not on dell01, 03 and 04)

host=`hostname | sed -e 's%build_.*%build%'`

check_host() {
  which rpm > /dev/null 2>&1
  rc=$?
  if [ "$rc" !=  "0" ]; then
    echo "Not an rpm based system."
  else
    dummy=`rpm -qf /etc/issue`
    case "$dummy" in 
      sles-release*)
        export QTDIR=/opt/qt/4.4.3
        echo "Is SLES"
        ;;
      openSUSE-release*)
        echo "Is SUSE"
      ;;
      centos-release*)
        export QTDIR=/opt/qt/4.4.3
        echo "Is CentOS"
      ;;
    esac
  fi

}

if [ "$host" != "build" ]; then
  exit
fi

check_host

export CTEST=/usr/bin/ctest

unset http_proxy

echo "Running ctest"

$CTEST -S ${HOME}/Dashboards/SDPANightly.cmake -V -VV

