
MAIN = concurrent

###############################################################################

NOT_STARTS_WITH += generate
NOT_STARTS_WITH += dup
NOT_STARTS_WITH += wait

###############################################################################

PUT_PORT = N=1000L

###############################################################################

WE_EXEC_LIBPATHS = $(SDPA_HOME)/libexec/sdpa

ifndef SDPA_HOME
 $(error variable SDPA_HOME not set)
endif

include $(SDPA_HOME)/share/sdpa/make/common.mk
