#!/bin/sh
if [ $# -lt 1 ]; then
  echo "usage: $0 node-number [node-number...]"
  exit 1
fi

if [ ! -r "$PBS_NODEFILE" ]; then
  echo "E: must be run on head node"
  exit 2
fi

ps aux | grep -q "[f]vm_sdpa_standalone"
if [ $? -ne 0 ]; then
  echo "E: FVM is not running, please start it first!"
  exit 2
fi

node_max=$( uniq $PBS_NODEFILE | wc -l )
for node_num in $*; do
  if [ $node_num -lt 1 -o $node_num -gt "$node_max" ]; then
	echo "E: node number out of range: must be within [1,$node_max]"
	exit 3
  fi

  node_name=$( uniq $PBS_NODEFILE | sort -n | tail -n +$node_num | head -n 1 )
  rm -f /scratch/$USER/sdpa/nre.$node_name.log
  rm -f /scratch/$USER/sdpa/pc.$node_name.log

  echo -n "starting nre on $node_name..."
  ssh $node_name $HOME/bin/start-nre >/dev/null 2>&1
  if [ $? -eq 0 ]; then
	echo "ok."
  else
	echo "failed."
	test -f /scratch/$USER/sdpa/nre.$node_name.log && echo "last 10 nre-log-lines" && tail -n 10 /scratch/$USER/sdpa/nre.$node_name.log
	test -f /scratch/$USER/sdpa/pc.$node_name.log && echo "last 10 pc-log-lines" && tail -n 10 /scratch/$USER/sdpa/pc.$node_name.log
  fi
done

