#!/bin/sh

if [ -r ~/.init-screen.env ]; then
    eval `cat .init-screen.env`
fi

if [ -r /p/herc/itwm/hpc/soft/sdpa/etc/sdpa.env ]; then
    source /p/herc/itwm/hpc/soft/sdpa/etc/sdpa.env
fi

name="nre.`hostname`"
agg="aggregator"
agg_host=
agg_port=5001
gui_url="lts016.itwm.fhg.de:9001"

if [ $# -ne 1 ]; then
  if [ -n "$SDPA_MASTER" ]; then
	agg_host="$SDPA_MASTER"
  else
	echo "E: i don't know where my aggregator is, sorry!"
	exit 1
  fi
else
	agg_host="$1"
fi
agg_url="$agg_host:$agg_port"

echo "using aggregator at: $agg_url"

echo -n "killing process-container..."
killall nre-pcd >/dev/null 2>&1
sleep 1
echo ""
echo -n "killing old nre..."
killall nre >/dev/null 2>&1
sleep 1
echo ""

FHGLOG_level=INFO nre-pcd -c /p/herc/itwm/hpc/soft/sdpa/fvm-pc/etc/fvm.cfg \
  /p/herc/itwm/hpc/ap/SDPA/playground/ap/mod/remig-mods/libinit.up8-mod.so \
  /p/herc/itwm/hpc/ap/SDPA/playground/ap/mod/remig-mods/libreadinp-mod.so \
  /p/herc/itwm/hpc/ap/SDPA/playground/ap/mod/remig-mods/libreadvelo-mod.so \
  /p/herc/itwm/hpc/ap/SDPA/playground/ap/mod/remig-mods/libcalc-mod.so \
  /p/herc/itwm/hpc/ap/SDPA/playground/ap/mod/remig-mods/libupdate-mod.so \
  /p/herc/itwm/hpc/ap/SDPA/playground/ap/mod/remig-mods/libprefsum-mod.so \
  /p/herc/itwm/hpc/ap/SDPA/playground/ap/mod/remig-mods/libwriteoutp-mod.so \
  /p/herc/itwm/hpc/ap/SDPA/playground/ap/mod/remig-mods/libfinalize-mod.so \
  >/scratch/petry/sdpa/pc.`hostname`.log 2>&1 &
sleep 1

FHGLOG_level=MIN /p/herc/itwm/hpc/soft/sdpa/sdpa/bin/nre --url "0.0.0.0" --name "$name" --gui_url="$gui_url" --agg_name="$agg" --agg_url="$agg_url" >/scratch/petry/sdpa/nre.`hostname`.log 2>&1 &
