
ifndef MAIN
  MAIN = sequence
endif

###############################################################################

#NOT_STARTS_WITH = generate

###############################################################################

PUT_PORT += n=5L

###############################################################################

ifndef SDPA_HOME
 $(error variable SDPA_HOME not set)
endif

include $(SDPA_HOME)/share/sdpa/make/common.mk
