#!/bin/bash

workdir=
sockets=
nodes=()

for arg
do
    case "$arg" in
        node=*)
            nodes+=(${arg#*=})
            ;;
        workdir=*)
            workdir=${arg#*=}
            ;;
        walltime=*)
            walltime=${arg#*=}
            ;;
        sockets=*)
            sockets=${arg#*=}
            ;;
        *)
            echo >&2 "$(basename $0): invalid argument: $arg"
            exit 1
            ;;
    esac
done

if [ -z "${workdir}" ]
then
    echo >&2 "workdir was not set"
    exit 77
fi

for node in ${nodes[@]}
do
    echo "$node 0 inuse $node is now in use ($workdir)"
done
