#!/bin/bash

workdir=
nodes=()

for arg
do
    case "$arg" in
        node=*)
            nodes+=(${arg#*=})
            ;;
        workdir=*)
            workdir=${arg#*=}
            ;;
        *)
            echo >&2 "$(basename $0): invalid argument: $arg"
            exit 1
            ;;
    esac
done

if [ -z "${workdir}" ]
then
    echo >&2 "workdir was not set"
    exit 77
fi

free_states=("free" "free/reserved" "addable" "addable/reserved")

for node in ${nodes[@]}
do
    t=$(( RANDOM % ${#free_states[@]} ))
    echo "$node 0 ${free_states[${t}]} is not in use anymore"
done
