
MAIN = n_of_m

###############################################################################

NOT_STARTS_WITH += scatter
NOT_STARTS_WITH += generate
NOT_STARTS_WITH += wait
NOT_STARTS_WITH += eat

###############################################################################

CXXLIBRARYPATHS += $(SDPA_HOME)/libexec/sdpa

###############################################################################

ifndef SDPA_HOME
 $(error variable SDPA_HOME not set)
endif

include $(SDPA_HOME)/share/sdpa/make/common.mk
