
MAIN = function_lookup

###############################################################################

PNETC_OPTS += --Windependent-transition OFF

###############################################################################

PNETC = /var/tmp/mr/xml/xml/parse/pnetc

ifndef SDPA_HOME
 $(error variable SDPA_HOME not set)
endif

include $(SDPA_HOME)/share/sdpa/make/common.mk
