#!/bin/sh

# This script is used on dell02.hpc.devnet for running the Nightly build of PreStackPro.
# It is executed via cron as user pspro (see crontab -e).
#
# It sets up some required environment variables, starts Xvnc so an X is available for the tests,
# then runs ctest which does the actual building and testing and kills Xvnc again afterwards.


# only do something on dell02 (and not on dell01, 03 and 04)

have_intel=no
host=`hostname | sed -e 's%build_.*%build%'`

check_host() {
  which rpm > /dev/null 2>&1
  rc=$?
  if [ "$rc" !=  "0" ]; then
    echo "Not an rpm based system."
  else
    dummy=`rpm -qf /etc/issue`
    case "$dummy" in 
      sles-release*)
##        export QTDIR=/opt/qt/4.4.3
##        export PATH=${QTDIR}/bin:$PATH
##	have_intel=yes
        echo "Is SLES"
        ;;
      openSUSE-release*)
##	have_intel=yes
        echo "Is SUSE"
      ;;
      centos-release*)
##        export QTDIR=/opt/qt/4.4.3
##        export PATH=${QTDIR}/bin:$PATH
        echo "Is CentOS"
      ;;
    esac
  fi

}

if [ "$host" != "build" ]; then
  exit
fi

#check_host

##export PKG_CONFIG_PATH=$PKG_CONFIG_PATH:/home/projects/genlm/external_software/log4cpp/1.0/lib/pkgconfig/
##export PKG_CONFIG_PATH=$PKG_CONFIG_PATH:/home/projects/genlm/external_software/activemq-cpp/2.1.3/lib/pkgconfig/
export LANG=en_US.UTF-8
export CTEST=/usr/bin/ctest

unset http_proxy

echo "Running ctest"

$CTEST -S ${HOME}/Dashboards.in/fhglogNightly.cmake -V -VV
rc=$?

echo "ctest returned: ${rc}"
