#!/bin/bash

. "${GSPC_EXEC_PATH}/gspc-sh-setup" || { echo >&2 "must be run by 'gspc'" ; exit 64; }

GSPC_API_COMMAND_SHORT_DESCRIPTION="checks whether a given port is open"
GSPC_API_COMMAND_LEVEL=-1

# return codes: 0 => port is open
#               1 => usage error
#               2 => port is closed
#               3 => host not found

function usage ()
{
    cat >&2 <<EOF
usage: check-port host port
EOF
}

if [ $# -ne 2 ]
then
    usage
    exit ${GSPC_EX_USAGE}
fi

node="${1}"; shift
port="${1}"; shift

nc=$(which netcat 2>/dev/null)
if [ -z "$nc" ] ; then
    nc=$(which nc 2>/dev/null)
    if [ -z "$nc" ] ; then
        gspc_log_error check-port "Neither 'netcat' nor 'nc' is available"
        exit ${GSPC_EX_OSFILE}
    fi
fi

gspc_log_trace check-port LANG=C "$nc" -w 1 "$node" "$port"
err=$(LANG=C "$nc" -w 1 "$node" "$port" </dev/null 2>&1)
ec=$?

if [ $ec -ne 0 ]
then
    if echo "$err" | grep -q -i 'name or service not known'
    then
        ec=3
    else
        ec=2
    fi
fi

gspc_log_debug check-port "[$node]:$port" "=>" "$ec" " -- $err"

exit $ec
