#!/bin/bash

GSPC_API_COMMAND_SHORT_DESCRIPTION="template GPI-Space command"
GSPC_API_COMMAND_LEVEL=-1

# levels: -1 - do not show in help output
#         >0 - show in help output of level L

. "${GSPC_EXEC_PATH}/gspc-sh-setup" || { echo >&2 "must be run by 'gspc'" ; exit 64; }

function usage()
{
    cat <<EOF
usage: <template> [-h|--help] [options]
EOF
}

if [ $# -eq 0 ] ; then usage ; exit 1 ; fi

TEMP=`getopt -o h --long help -n 'template' -- "$@"`

if [ $? != 0 ] ; then echo >&2 "try '-h' or '--help'. Terminating..." ; exit 1 ; fi

eval set -- "$TEMP"

while true ; do
    case "$1" in
        -h|--help) usage; exit 0 ;;
        --) shift; break ;;
        *) gspc_log_error template "Internal error on argument: '$1'"; exit 1 ;;
    esac
done
