#!/bin/bash

GSPC_API_COMMAND_SHORT_DESCRIPTION="shutdown the RIF"
GSPC_API_COMMAND_LEVEL=2

. "${GSPC_EXEC_PATH}/gspc-sh-setup" || { echo >&2 "must be run by 'gspc'" ; exit 64; }

function usage()
{
    cat <<EOF
usage: rif-shutdown [-h|--help] [options]

Options:

   --rif-port <port>     specify the rif-port to use

   -F|--file file        use nodes from file
   -N|--node node        use this node
EOF
}

opts=()
while true ; do
    case "$1" in
        -h|--help) usage ; exit ${GSPC_EX_OK} ;;
        --rif-port)
            opts+=("$1" "$2")
            shift; shift
            ;;
        -F|--file)
            opts+=("$1" "$2")
            shift; shift
            ;;
        -N|--node)
            opts+=("$1" "$2")
            shift; shift
            ;;
        --fanout)
            opts+=("$1" "$2")
            shift; shift
            ;;
        --sync)
            opts+=("$1")
            shift
            ;;
        --) shift; break ;;
        *) break ;;
    esac
done

for n
do
    opts+=(-N "$n")
done

gspc rif raw "${opts[@]}" shutdown
