
MAIN = use_template_with_module_call

###############################################################################

PUT_PORT = x=[]

###############################################################################

ifndef SDPA_HOME
 $(error variable SDPA_HOME not set)
endif

include $(SDPA_HOME)/share/sdpa/make/common.mk
