
MAIN = split_join

###############################################################################

PUT_PORT += I=10L

###############################################################################

ifndef SDPA_HOME
 $(error variable SDPA_HOME not set)
endif

include $(SDPA_HOME)/share/sdpa/make/common.mk
