/*
 * ex: set ro:
 * DO NOT EDIT.
 * generated by smc (http://smc.sourceforge.net/)
 * from file : PerformanceTest.sm
 */

#include <tests/sdpa/PerformanceTestFSMEvent.hpp>
#include "test_FSMPerformance.hpp"
#include "PerformanceTest_sm.h"

using namespace statemap;

namespace sdpa
{
    namespace tests
    {
        // Static class declarations.
        PerformanceTest_S0 PerformanceTest::S0("PerformanceTest::S0", 0);
        PerformanceTest_S1 PerformanceTest::S1("PerformanceTest::S1", 1);

        void FSMPerformanceTestState::T(FSMPerformanceTestContext& context, const ::sdpa::tests::PerformanceTestFSMEvent& e)
        {
            Default(context);
            return;
        }

        void FSMPerformanceTestState::Default(FSMPerformanceTestContext& context)
        {
            throw (
                TransitionUndefinedException(
                    context.getState().getName(),
                    context.getTransition()));

            return;
        }

        void PerformanceTest_S0::T(FSMPerformanceTestContext& context, const ::sdpa::tests::PerformanceTestFSMEvent& e)
        {
            FSMPerformanceTest& ctxt(context.getOwner());

            (context.getState()).Exit(context);
            context.clearState();
            try
            {
                ctxt.do_s0_s1(e);
                context.setState(PerformanceTest::S1);
            }
            catch (...)
            {
                context.setState(PerformanceTest::S1);
                throw;
            }
            (context.getState()).Entry(context);

            return;
        }

        void PerformanceTest_S1::T(FSMPerformanceTestContext& context, const ::sdpa::tests::PerformanceTestFSMEvent& e)
        {
            FSMPerformanceTest& ctxt(context.getOwner());

            (context.getState()).Exit(context);
            context.clearState();
            try
            {
                ctxt.do_s1_s0(e);
                context.setState(PerformanceTest::S0);
            }
            catch (...)
            {
                context.setState(PerformanceTest::S0);
                throw;
            }
            (context.getState()).Entry(context);

            return;
        }
    }
}

/*
 * Local variables:
 *  buffer-read-only: t
 * End:
 */
