
MAIN = mapreduce

###############################################################################

PUT_PORT += I=Struct[]

###############################################################################

ifndef SDPA_HOME
 $(error variable SDPA_HOME not set)
endif

include $(SDPA_HOME)/share/sdpa/make/common.mk
