#!/bin/sh
if [ ! -r "$PBS_NODEFILE" ]; then
  echo "E: must be run on head node"
  exit 2
fi

node_max=$( uniq $PBS_NODEFILE | wc -l )
nodes=$@
if [ $# -lt 1 ]; then
  echo "killing all NREs..."
  nodes=$( echo $( seq 1 $node_max ) )
fi

for node_num in $nodes; do
  if [ $node_num -lt 1 -o $node_num -gt "$node_max" ]; then
	echo "E: node number out of range: must be within [1,$node_max]"
	exit 3
  fi

  node_name=$( uniq $PBS_NODEFILE | sort -n | tail -n +$node_num | head -n 1 )
  echo -n "killing nre on $node_name..."
  ssh $node_name killall nre-pcd >/dev/null 2>&1
  ssh $node_name killall nre >/dev/null 2>&1
  echo "done."
done

