#!/bin/sh
agg_port=5001
orch_host=
orch_port=5000
if [ $# -ne 1 ]; then
  if [ -n "$SDPA_MASTER" ]; then
	orch_host="$SDPA_MASTER"
  else
	orch_host="`hostname`"
	echo "assuming orchestrator on same node: $orch_host"
  fi
else
  orch_host="$1"
fi
orch_url="$orch_host:$orch_port"
echo "Running Aggregator at: `hostname`:$agg_port"
echo "using orchestrator at: $orch_url"

FHGLOG_level=DEBUG /p/herc/itwm/hpc/soft/sdpa/sdpa/bin/aggregator -n aggregator -m orchestrator -p $orch_url -u 0.0.0.0:$agg_port >/scratch/petry/sdpa/agg.log 2>&1
