// Copyright (C) 2023 Fraunhofer ITWM
// SPDX-License-Identifier: GPL-3.0-or-later

#include <util-generic/va_args.hpp>

#include <boost/test/unit_test.hpp>

namespace fhg
{
  namespace util
  {
    //! \todo is there some absurd way we could implement this?
#define REQUIRE_COMPILE_ERR(...)

    BOOST_AUTO_TEST_CASE (required_va_arg)
    {
      REQUIRE_COMPILE_ERR (FHG_UTIL_REQUIRED_VA_ARG (1)                     );
      BOOST_REQUIRE_EQUAL (FHG_UTIL_REQUIRED_VA_ARG (1,    1)            , 1);
      BOOST_REQUIRE_EQUAL (FHG_UTIL_REQUIRED_VA_ARG (1,    1, 2)         , 1);
      BOOST_REQUIRE_EQUAL (FHG_UTIL_REQUIRED_VA_ARG (1,    1, 2, 3)      , 1);
      BOOST_REQUIRE_EQUAL (FHG_UTIL_REQUIRED_VA_ARG (1,    1, 2, 3, 4)   , 1);
      BOOST_REQUIRE_EQUAL (FHG_UTIL_REQUIRED_VA_ARG (1,    1, 2, 3, 4, 5), 1);

      REQUIRE_COMPILE_ERR (FHG_UTIL_REQUIRED_VA_ARG (2)                     );
      REQUIRE_COMPILE_ERR (FHG_UTIL_REQUIRED_VA_ARG (2,    1)               );
      BOOST_REQUIRE_EQUAL (FHG_UTIL_REQUIRED_VA_ARG (2,    1, 2)         , 2);
      BOOST_REQUIRE_EQUAL (FHG_UTIL_REQUIRED_VA_ARG (2,    1, 2, 3)      , 2);
      BOOST_REQUIRE_EQUAL (FHG_UTIL_REQUIRED_VA_ARG (2,    1, 2, 3, 4)   , 2);
      BOOST_REQUIRE_EQUAL (FHG_UTIL_REQUIRED_VA_ARG (2,    1, 2, 3, 4, 5), 2);

      REQUIRE_COMPILE_ERR (FHG_UTIL_REQUIRED_VA_ARG (3)                     );
      REQUIRE_COMPILE_ERR (FHG_UTIL_REQUIRED_VA_ARG (3,    1)               );
      REQUIRE_COMPILE_ERR (FHG_UTIL_REQUIRED_VA_ARG (3,    1, 2)            );
      BOOST_REQUIRE_EQUAL (FHG_UTIL_REQUIRED_VA_ARG (3,    1, 2, 3)      , 3);
      BOOST_REQUIRE_EQUAL (FHG_UTIL_REQUIRED_VA_ARG (3,    1, 2, 3, 4)   , 3);
      BOOST_REQUIRE_EQUAL (FHG_UTIL_REQUIRED_VA_ARG (3,    1, 2, 3, 4, 5), 3);

      REQUIRE_COMPILE_ERR (FHG_UTIL_REQUIRED_VA_ARG (4)                     );
      REQUIRE_COMPILE_ERR (FHG_UTIL_REQUIRED_VA_ARG (4,    1)               );
      REQUIRE_COMPILE_ERR (FHG_UTIL_REQUIRED_VA_ARG (4,    1, 2)            );
      REQUIRE_COMPILE_ERR (FHG_UTIL_REQUIRED_VA_ARG (4,    1, 2, 3)         );
      BOOST_REQUIRE_EQUAL (FHG_UTIL_REQUIRED_VA_ARG (4,    1, 2, 3, 4)   , 4);
      BOOST_REQUIRE_EQUAL (FHG_UTIL_REQUIRED_VA_ARG (4,    1, 2, 3, 4, 5), 4);

      REQUIRE_COMPILE_ERR (FHG_UTIL_REQUIRED_VA_ARG (5)                     );
      REQUIRE_COMPILE_ERR (FHG_UTIL_REQUIRED_VA_ARG (5,    1)               );
      REQUIRE_COMPILE_ERR (FHG_UTIL_REQUIRED_VA_ARG (5,    1, 2)            );
      REQUIRE_COMPILE_ERR (FHG_UTIL_REQUIRED_VA_ARG (5,    1, 2, 3)         );
      REQUIRE_COMPILE_ERR (FHG_UTIL_REQUIRED_VA_ARG (5,    1, 2, 3, 4)      );
      BOOST_REQUIRE_EQUAL (FHG_UTIL_REQUIRED_VA_ARG (5,    1, 2, 3, 4, 5), 5);
    }

    BOOST_AUTO_TEST_CASE (optional_va_arg)
    {
      REQUIRE_COMPILE_ERR (FHG_UTIL_OPTIONAL_VA_ARG (1, 1)                  );
      BOOST_REQUIRE_EQUAL (FHG_UTIL_OPTIONAL_VA_ARG (1, 1, 1)            , 1);
      BOOST_REQUIRE_EQUAL (FHG_UTIL_OPTIONAL_VA_ARG (1, 1, 1, 2)         , 1);
      BOOST_REQUIRE_EQUAL (FHG_UTIL_OPTIONAL_VA_ARG (1, 1, 1, 2, 3)      , 1);
      BOOST_REQUIRE_EQUAL (FHG_UTIL_OPTIONAL_VA_ARG (1, 1, 1, 2, 3, 4)   , 1);

      REQUIRE_COMPILE_ERR (FHG_UTIL_OPTIONAL_VA_ARG (2, 1)                  );
      BOOST_REQUIRE_EQUAL (FHG_UTIL_OPTIONAL_VA_ARG (2, 1, 1)            , 1);
      BOOST_REQUIRE_EQUAL (FHG_UTIL_OPTIONAL_VA_ARG (2, 1, 1, 2)         , 2);
      BOOST_REQUIRE_EQUAL (FHG_UTIL_OPTIONAL_VA_ARG (2, 1, 1, 2, 3)      , 2);
      BOOST_REQUIRE_EQUAL (FHG_UTIL_OPTIONAL_VA_ARG (2, 1, 1, 2, 3, 4)   , 2);

      REQUIRE_COMPILE_ERR (FHG_UTIL_OPTIONAL_VA_ARG (2, 2)                  );
      REQUIRE_COMPILE_ERR (FHG_UTIL_OPTIONAL_VA_ARG (2, 2, 1)               );
      BOOST_REQUIRE_EQUAL (FHG_UTIL_OPTIONAL_VA_ARG (2, 2, 1, 2)         , 2);
      BOOST_REQUIRE_EQUAL (FHG_UTIL_OPTIONAL_VA_ARG (2, 2, 1, 2, 3)      , 2);
      BOOST_REQUIRE_EQUAL (FHG_UTIL_OPTIONAL_VA_ARG (2, 2, 1, 2, 3, 4)   , 2);

      REQUIRE_COMPILE_ERR (FHG_UTIL_OPTIONAL_VA_ARG (3, 1)                  );
      BOOST_REQUIRE_EQUAL (FHG_UTIL_OPTIONAL_VA_ARG (3, 1, 1)            , 1);
      BOOST_REQUIRE_EQUAL (FHG_UTIL_OPTIONAL_VA_ARG (3, 1, 1, 2)         , 1);
      BOOST_REQUIRE_EQUAL (FHG_UTIL_OPTIONAL_VA_ARG (3, 1, 1, 2, 3)      , 3);
      BOOST_REQUIRE_EQUAL (FHG_UTIL_OPTIONAL_VA_ARG (3, 1, 1, 2, 3, 4)   , 3);

      REQUIRE_COMPILE_ERR (FHG_UTIL_OPTIONAL_VA_ARG (3, 2)                  );
      REQUIRE_COMPILE_ERR (FHG_UTIL_OPTIONAL_VA_ARG (3, 2, 1)               );
      BOOST_REQUIRE_EQUAL (FHG_UTIL_OPTIONAL_VA_ARG (3, 2, 1, 2)         , 2);
      BOOST_REQUIRE_EQUAL (FHG_UTIL_OPTIONAL_VA_ARG (3, 2, 1, 2, 3)      , 3);
      BOOST_REQUIRE_EQUAL (FHG_UTIL_OPTIONAL_VA_ARG (3, 2, 1, 2, 3, 4)   , 3);

      REQUIRE_COMPILE_ERR (FHG_UTIL_OPTIONAL_VA_ARG (3, 3)                  );
      REQUIRE_COMPILE_ERR (FHG_UTIL_OPTIONAL_VA_ARG (3, 3, 1)               );
      REQUIRE_COMPILE_ERR (FHG_UTIL_OPTIONAL_VA_ARG (3, 3, 1, 2)            );
      BOOST_REQUIRE_EQUAL (FHG_UTIL_OPTIONAL_VA_ARG (3, 3, 1, 2, 3)      , 3);
      BOOST_REQUIRE_EQUAL (FHG_UTIL_OPTIONAL_VA_ARG (3, 3, 1, 2, 3, 4)   , 3);

      REQUIRE_COMPILE_ERR (FHG_UTIL_OPTIONAL_VA_ARG (4, 2)                  );
      REQUIRE_COMPILE_ERR (FHG_UTIL_OPTIONAL_VA_ARG (4, 2, 1)               );
      BOOST_REQUIRE_EQUAL (FHG_UTIL_OPTIONAL_VA_ARG (4, 2, 1, 2)         , 2);
      BOOST_REQUIRE_EQUAL (FHG_UTIL_OPTIONAL_VA_ARG (4, 2, 1, 2, 3)      , 2);
      BOOST_REQUIRE_EQUAL (FHG_UTIL_OPTIONAL_VA_ARG (4, 2, 1, 2, 3, 4)   , 4);
      BOOST_REQUIRE_EQUAL (FHG_UTIL_OPTIONAL_VA_ARG (4, 2, 1, 2, 3, 4, 5), 4);

      REQUIRE_COMPILE_ERR (FHG_UTIL_OPTIONAL_VA_ARG (4, 3)                  );
      REQUIRE_COMPILE_ERR (FHG_UTIL_OPTIONAL_VA_ARG (4, 3, 1)               );
      REQUIRE_COMPILE_ERR (FHG_UTIL_OPTIONAL_VA_ARG (4, 3, 1, 2)            );
      BOOST_REQUIRE_EQUAL (FHG_UTIL_OPTIONAL_VA_ARG (4, 3, 1, 2, 3)      , 3);
      BOOST_REQUIRE_EQUAL (FHG_UTIL_OPTIONAL_VA_ARG (4, 3, 1, 2, 3, 4)   , 4);
      BOOST_REQUIRE_EQUAL (FHG_UTIL_OPTIONAL_VA_ARG (4, 3, 1, 2, 3, 4, 5), 4);

      REQUIRE_COMPILE_ERR (FHG_UTIL_OPTIONAL_VA_ARG (4, 4)                  );
      REQUIRE_COMPILE_ERR (FHG_UTIL_OPTIONAL_VA_ARG (4, 4, 1)               );
      REQUIRE_COMPILE_ERR (FHG_UTIL_OPTIONAL_VA_ARG (4, 4, 1, 2)            );
      REQUIRE_COMPILE_ERR (FHG_UTIL_OPTIONAL_VA_ARG (4, 4, 1, 2, 3)         );
      BOOST_REQUIRE_EQUAL (FHG_UTIL_OPTIONAL_VA_ARG (4, 4, 1, 2, 3, 4)   , 4);
      BOOST_REQUIRE_EQUAL (FHG_UTIL_OPTIONAL_VA_ARG (4, 4, 1, 2, 3, 4, 5), 4);

      REQUIRE_COMPILE_ERR (FHG_UTIL_OPTIONAL_VA_ARG (5, 3)                  );
      REQUIRE_COMPILE_ERR (FHG_UTIL_OPTIONAL_VA_ARG (5, 3, 1)               );
      REQUIRE_COMPILE_ERR (FHG_UTIL_OPTIONAL_VA_ARG (5, 3, 1, 2)            );
      BOOST_REQUIRE_EQUAL (FHG_UTIL_OPTIONAL_VA_ARG (5, 3, 1, 2, 3)      , 3);
      BOOST_REQUIRE_EQUAL (FHG_UTIL_OPTIONAL_VA_ARG (5, 3, 1, 2, 3, 4)   , 3);
      BOOST_REQUIRE_EQUAL (FHG_UTIL_OPTIONAL_VA_ARG (5, 3, 1, 2, 3, 4, 5), 5);

      REQUIRE_COMPILE_ERR (FHG_UTIL_OPTIONAL_VA_ARG (5, 4)                  );
      REQUIRE_COMPILE_ERR (FHG_UTIL_OPTIONAL_VA_ARG (5, 4, 1)               );
      REQUIRE_COMPILE_ERR (FHG_UTIL_OPTIONAL_VA_ARG (5, 4, 1, 2)            );
      REQUIRE_COMPILE_ERR (FHG_UTIL_OPTIONAL_VA_ARG (5, 4, 1, 2, 3)         );
      BOOST_REQUIRE_EQUAL (FHG_UTIL_OPTIONAL_VA_ARG (5, 4, 1, 2, 3, 4)   , 4);
      BOOST_REQUIRE_EQUAL (FHG_UTIL_OPTIONAL_VA_ARG (5, 4, 1, 2, 3, 4, 5), 5);

      REQUIRE_COMPILE_ERR (FHG_UTIL_OPTIONAL_VA_ARG (5, 5)                  );
      REQUIRE_COMPILE_ERR (FHG_UTIL_OPTIONAL_VA_ARG (5, 5, 1)               );
      REQUIRE_COMPILE_ERR (FHG_UTIL_OPTIONAL_VA_ARG (5, 5, 1, 2)            );
      REQUIRE_COMPILE_ERR (FHG_UTIL_OPTIONAL_VA_ARG (5, 5, 1, 2, 3)         );
      REQUIRE_COMPILE_ERR (FHG_UTIL_OPTIONAL_VA_ARG (5, 5, 1, 2, 3, 4)      );
      BOOST_REQUIRE_EQUAL (FHG_UTIL_OPTIONAL_VA_ARG (5, 5, 1, 2, 3, 4, 5), 5);
    }
  }
}
