# Tries to locate a logging framework.
# This file defines:
# * LOG4CPP_FOUND if log4cpp was found
# * LOG4CPP_LIBRARIES The lib to link to (currently only a static unix lib, not portable) 
# * LOG4CPP_LIBRARY_DIRS The path to the library directory
# * LOG4CPP_INCLUDE_DIRS The path to the include directory

message(STATUS "FindLogging check")
IF (NOT WIN32)
  include(FindPkgConfig)
  if ( PKG_CONFIG_FOUND )

     pkg_check_modules (PC_LOG4CPP REQUIRED log4cpp>=1.0)

     set(LOG4CPP_DEFINITIONS ${PC_LOG4CPP_CFLAGS_OTHER})
  endif(PKG_CONFIG_FOUND)
endif (NOT WIN32)

FIND_PATH(LOG4CPP_INCLUDE_DIRS log4cpp/Category.hh
   HINTS
     ${PC_LOG4CPP_INCLUDEDIR}
     ${PC_LOG4CPP_INCLUDE_DIRS}
    ${CMAKE_INCLUDE_PATH}
    $ENV{LOG4CPP_HOME}/include
)

SET(LOG4CPP_LIBRARY_NAMES ${LOG4CPP_LIBRARY_NAMES} liblog4cpp.a)
FIND_LIBRARY(LOG4CPP_LIBRARY NAMES ${LOG4CPP_LIBRARY_NAMES}
  HINTS
    ${PC_LOG4CPP_LIBDIR}
    ${PC_LOG4CPP_LIBRARY_DIRS}
    $ENV{LOG4CPP_HOME}/lib
)

#


# if the include and the program are found then we have it
IF(LOG4CPP_LIBRARY AND LOG4CPP_INCLUDE_DIRS) 
    message(STATUS "Found log4cpp: -I${LOG4CPP_INCLUDE_DIRS} ${LOG4CPP_LIBRARY}")
    GET_FILENAME_COMPONENT (LOG4CPP_LIBRARY_DIRS ${LOG4CPP_LIBRARY} PATH)
    GET_FILENAME_COMPONENT (LOG4CPP_LIBRARIES ${LOG4CPP_LIBRARY} NAME)
    SET(LOG4CPP_FOUND "YES")
ENDIF(LOG4CPP_LIBRARY AND LOG4CPP_INCLUDE_DIRS)

  message("  LOG4CPP 1: -I${LOG4CPP_STATIC_INCLUDE_DIRS} -L${LOG4CPP_STATIC_LIBRARY_DIRS} -l${LOG4CPP_STATIC_LIBRARIES}")
  message("  LOG4CPP 2: -I${LOG4CPP_INCLUDE_DIRS} -L${LOG4CPP_LIBRARY_DIRS} ${LOG4CPP_LIBRARIES} ${LOG4CPP_LIBRARY}")

set(LOG4CPP_STATIC_INCLUDE_DIRS ${LOG4CPP_INCLUDE_DIRS} PARENT_SCOPE)
set(LOG4CPP_STATIC_LIBRARY_DIRS ${LOG4CPP_LIBRARY_DIRS} PARENT_SCOPE)
set(LOG4CPP_STATIC_LIBRARIES ${LOG4CPP_LIBRARIES} PARENT_SCOPE)

MARK_AS_ADVANCED(
  LOG4CPP_LIBRARY
  LOG4CPP_LIBRARIES
  LOG4CPP_LIBRARY_DIRS
  LOG4CPP_INCLUDE_DIRS
)
