# -*- mode: cmake; -*-
# bernd.loerwald@itwm.fraunhofer.de

# GRAPHVIZ_FOUND - system has Graphviz
# GRAPHVIZ_INCLUDE_DIR - the Graphviz include directory
# GRAPHVIZ_CDT_LIBRARY, GRAPHVIZ_GVC_LIBRARY, GRAPHVIZ_CGRAPH_LIBRARY
# GRAPHVIZ_GRAPH_LIBRARY, GRAPHVIZ_PATHPLAN_LIBRARY
# GRAPHVIZ_LIBRARIES - all of the above for lazy people. (me)

if (GRAPHVIZ_INCLUDE_DIR AND GRAPHVIZ_CDT_LIBRARY AND
    GRAPHVIZ_CGRAPH_LIBRARY AND GRAPHVIZ_GRAPH_LIBRARY AND
    GRAPHVIZ_PATHPLAN_LIBRARY)
    set (GRAPHVIZ_FIND_QUIETLY TRUE)
endif (GRAPHVIZ_INCLUDE_DIR AND GRAPHVIZ_CDT_LIBRARY AND
  GRAPHVIZ_CGRAPH_LIBRARY AND GRAPHVIZ_GRAPH_LIBRARY AND
  GRAPHVIZ_PATHPLAN_LIBRARY)

find_path (GRAPHVIZ_INCLUDE_DIR gvc.h PATH_SUFFIXES graphviz)

find_library (GRAPHVIZ_CDT_LIBRARY NAMES cdt
  PATH_SUFFIXES  graphviz
)
find_library (GRAPHVIZ_GVC_LIBRARY NAMES gvc
  PATH_SUFFIXES  graphviz
)
# not in graphviz-2.6
#find_library (GRAPHVIZ_CGRAPH_LIBRARY NAMES cgraph
#  PATH_SUFFIXES  graphviz
#)
find_library (GRAPHVIZ_GRAPH_LIBRARY NAMES graph
  PATH_SUFFIXES  graphviz
)
find_library (GRAPHVIZ_PATHPLAN_LIBRARY NAMES pathplan
  PATH_SUFFIXES  graphviz
)

if (GRAPHVIZ_INCLUDE_DIR AND GRAPHVIZ_CDT_LIBRARY AND
    GRAPHVIZ_GVC_LIBRARY AND GRAPHVIZ_CGRAPH_LIBRARY AND
    GRAPHVIZ_GRAPH_LIBRARY AND GRAPHVIZ_PATHPLAN_LIBRARY)
   set (GRAPHVIZ_FOUND TRUE)
else (GRAPHVIZ_INCLUDE_DIR AND GRAPHVIZ_CDT_LIBRARY AND
    GRAPHVIZ_GVC_LIBRARY AND GRAPHVIZ_CGRAPH_LIBRARY AND
    GRAPHVIZ_GRAPH_LIBRARY AND GRAPHVIZ_PATHPLAN_LIBRARY)
   set (GRAPHVIZ_FOUND FALSE)
endif (GRAPHVIZ_INCLUDE_DIR AND GRAPHVIZ_CDT_LIBRARY AND
  GRAPHVIZ_GVC_LIBRARY AND GRAPHVIZ_CGRAPH_LIBRARY AND
  GRAPHVIZ_GRAPH_LIBRARY AND GRAPHVIZ_PATHPLAN_LIBRARY)

set (GRAPHVIZ_LIBRARIES ${GRAPHVIZ_CDT_LIBRARY} ${GRAPHVIZ_GVC_LIBRARY} ${GRAPHVIZ_CGRAPH_LIBRARY} ${GRAPHVIZ_GRAPH_LIBRARY} ${GRAPHVIZ_PATHPLAN_LIBRARY})

IF (GRAPHVIZ_FOUND)
  IF (NOT GRAPHVIZ_FIND_QUIETLY)
    MESSAGE (STATUS "Found Graphviz: ${GRAPHVIZ_INCLUDE_DIR}, ${GRAPHVIZ_CDT_LIBRARY} ${GRAPHVIZ_GVC_LIBRARY} ${GRAPHVIZ_CGRAPH_LIBRARY} ${GRAPHVIZ_GRAPH_LIBRARY} ${GRAPHVIZ_PATHPLAN_LIBRARY}")
  ENDIF (NOT GRAPHVIZ_FIND_QUIETLY)
ELSE (GRAPHVIZ_FOUND)
  IF (GRAPHVIZ_FIND_REQUIRED)
    MESSAGE (FATAL_ERROR "Could NOT find Graphivz")
  ENDIF (GRAPHVIZ_FIND_REQUIRED)
ENDIF (GRAPHVIZ_FOUND)

# show the GRAPHVIZ_INCLUDE_DIR AND GRAPHVIZ_LIBRARIES variables only in the advanced view
MARK_AS_ADVANCED(
    GRAPHVIZ_FOUND
    GRAPHVIZ_INCLUDE_DIR
    GRAPHVIZ_GVC_LIBRARY
    GRAPHVIZ_CGRAPH_LIBRARY
    GRAPHVIZ_GRAPH_LIBRARY
    GRAPHVIZ_LIBRARIES
)
