#!/bin/bash

data_dir=${DATA_DIR:?}

filter_dir="$data_dir/filter"
filter_cfg="$filter_dir/filt.conf"
tune_cfg="$filter_dir/tune.conf"
pnet_lib="$data_dir/../pnet/lib"
pnet_lib="/p/herc/itwm/hpc/ap/SDPA/application/lib"

if [ $# -lt 5 ]; then
  echo "usage: $0 input-file input-type output-file output-type su-pipeline"
  exit 1
fi

inf=${1:?}
int=${2:?}
outf=${3:?}
outt=${4:?}
prog=${5:?}
shift 5

if [ ! -r "$inf" ] ; then
  echo "E: cannot access $inf for reading, aborting" >/dev/stderr
  exit 1
fi

if [ -r "$tune_cfg" ] ; then
  cat "$tune_cfg" > "$filter_cfg"
else
  echo "W: could not read $tune_cfg" >/dev/stderr
fi

abspath ()
{
  p="$1"
  case "$p" in
	/*)
	  REPLY="$p"
	  ;;
	*)
	  REPLY="`pwd`/$p"
	  ;;
  esac
  return 0
}

abspath ${inf}
abs_inf="$REPLY"

abspath ${outf}
abs_outf="$REPLY"

# create the shell script to execute the filter
script=$( mktemp "$filter_dir/filter.sh.XXXXXX" )
if [ $? -ne 0 ] ; then
  echo "could not create temporary file in $filter_dir" >/dev/stderr
  exit 2
fi

cat > "$script" <<EOF
#!/bin/bash
$prog $@
EOF
chmod +x "${script}"

cat >> "$filter_cfg" <<EOF
input.file ${abs_inf}
input.type ${int}
output.file ${abs_outf}
output.type ${outt}
exec.su "${script}"
EOF

cleanup ()
{
  rm -f "${script}"
  rm -f "${filter_cfg}"
}
trap cleanup EXIT

echo "-: generated script file:" >/dev/stderr
cat "${script}" >/dev/stderr

echo "-: generated config:" >/dev/stderr
cat "${filter_cfg}" >/dev/stderr

echo -n "-: generating job description..." >/dev/stderr
sed -e "s,@CONFIG_FILE@,$filter_cfg," "$filter_dir/loop.xml.in" > "$filter_dir/loop.xml"
if [ $? -ne 0 ] ; then
  echo "E: generating failed!" >/dev/stderr
  exit 2
fi
echo "ok" >/dev/stderr

echo -n "-: compiling job description..." >/dev/stderr
pnetc "$filter_dir/loop.xml" -I "$pnet_lib" > "$filter_dir/su4.pnet"
if [ $? -ne 0 ] ; then
  echo "E: generating failed!"
  exit 2
fi
echo "ok" >/dev/stderr

exit 0

sdpac -w submit $filter_dir/su4.pnet
test -e "${script}" && rm -f "${script}"
