#!/bin/bash

dst="$1"

if [ ! -r "${dst}/libexec/sdpa/apps/frtm/hooks/setup.sh" ]
then
    echo >&2 "FRTM was not included"
    exit 0
fi

sed -i \
    -e "s,^RTM_HOME=.*$,RTM_HOME=\"${dst}/libexec/sdpa/apps/frtm\","  \
    -e "s,^SDPA_HOME=.*$,SDPA_HOME=\"${dst}\"," \
    -e "s,^RESERVED_NODES=.*$,RESERVED_NODES=\"\"," \
    "${dst}/libexec/sdpa/apps/frtm/hooks/setup.sh"

echo >&2 "FRTM configured"
