#!/bin/bash

# query user information here and create
#   ${dst}/etc/sdpa/defaults

dst="$1"

opt_cluster_head=$(hostname)
read -e -p "Head node of the cluster [$opt_cluster_head]:" val
if [ -n "$val" ]
then
    opt_cluster_head="${val}"
fi
unset val

opt_enable_gpi=false
read -e -p "Enable GPI [$opt_enable_gpi]:" val
if [ -n "$val" ]
then
    opt_enable_gpi="${val}"
fi
unset val

cat > "${dst}/etc/sdpa/defaults" <<EOF
DEFAULT_CLUSTER_HEAD="${opt_cluster_head}"
DEFAULT_GPI_ENABLED="${opt_enable_gpi}"
EOF

if [ $VERBOSE -gt 0 ]
then
    echo >&2 "set cluster head node to := '${opt_cluster_head}'"
    echo >&2 "set gpi enabled to := '${opt_enable_gpi}'"
fi
