MAIN = workerlist

###############################################################################

NOT_STARTS_WITH += generate

###############################################################################

CXXLIBRARYPATHS += $(SDPA_HOME)/lib

###############################################################################

PUT_PORT += trigger=[]

###############################################################################

ifndef SDPA_HOME
 $(error variable SDPA_HOME not set)
endif

include $(SDPA_HOME)/share/sdpa/make/common.mk

WE_EXEC_LIBPATHS = $(SDPA_HOME)/libexec/sdpa
