#!/bin/sh

# This script is used on dell02.hpc.devnet to run the Continuous build of PreStackPro.
# It is started via cron as user pspro (see crontab -e).
# It sets up some required environment variables, sets up the Intel compiler, and then runs ctest.

check_host() {
  which rpm > /dev/null 2>&1
  rc=$?
  if [ "$rc" !=  "0" ]; then
    echo "Not an rpm based system."
  else
    dummy=`rpm -qf /etc/issue`
    case "$dummy" in
      sles-release*)
        export QTDIR=/opt/qt/4.4.3
	export PATH=${QTDIR}/bin:$PATH
        echo "Is SLES"
        ;;
      openSUSE-release*)
        echo "Is SUSE"
      ;;
      centos-release*)
        export QTDIR=/opt/qt/4.4.3
	export PATH=${QTDIR}/bin:$PATH
        echo "Is CentOS"
      ;;
    esac
  fi

}

host=`hostname | sed -e 's%build_.*%build%'`

if [ "$host" != "build" ]; then
  exit
fi

#check_host

export PKG_CONFIG_PATH=$PKG_CONFIG_PATH:/home/projects/genlm/external_software/log4cpp/1.0/lib/pkgconfig/
export PKG_CONFIG_PATH=$PKG_CONFIG_PATH:/home/projects/genlm/external_software/activemq-cpp/2.1.3/lib/pkgconfig/
export LANG=en_US.UTF-8
export CTEST=//usr/bin/ctest

unset http_proxy

echo "Running ctest"

# set additional directory where cmake will search for stuff:
#export CMAKE_PREFIX_PATH=/p/hpc/psp/vr3-nightly-test-support

$CTEST -V -S ${HOME}/Dashboards/GenLMContinuous.cmake
